### ISSUE TITLE
Make the dataset available for users outside China

### ISSUE THREAD

**Issue by stymbhrdwj** [yunhao-zou/RawHDR#2]
I cannot access the dataset via [pan.baidu.com](https://pan.baidu.com/s/1HOxGhTEY9whGxbEEw1QAjw?_at_=1694366519816) as I am unable to register for a Baidu account with an Indian mobile number. I kindly request the authors to also share the dataset on a globally accessible cloud service e.g. Google Drive or Microsoft OneDrive.

Thank you.

**Comment by yunhao-zou** [comment]
Sure! Here is the [**OneDrive**](https://1drv.ms/f/s!AuA3qjJbfh9FiGTQqmw9U4z-vlKw?e=L9bCLg) link.
